// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9vnuYf-nm4_id1oxsv9ZCFzsT2-8CBM',
    appId: '1:1014544687009:web:8c7b46295f25b3f4ec75e0',
    messagingSenderId: '1014544687009',
    projectId: 'terrace-lumina',
    authDomain: 'terrace-lumina.firebaseapp.com',
    storageBucket: 'terrace-lumina.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk6Cpbgm79cTNfPIT6yy8k6YGE7qaKvjY',
    appId: '1:1014544687009:android:74e2c9eb532cad9fec75e0',
    messagingSenderId: '1014544687009',
    projectId: 'terrace-lumina',
    storageBucket: 'terrace-lumina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9A883VmhY3jEcHTCuM8bpum6MBukoSk',
    appId: '1:1014544687009:ios:4088231cba556e58ec75e0',
    messagingSenderId: '1014544687009',
    projectId: 'terrace-lumina',
    storageBucket: 'terrace-lumina.firebasestorage.app',
    iosBundleId: 'com.lumina.terrace',
  );
}
